### ISSUE TITLE
스페이스 추가하기

### ISSUE THREAD

**Issue by jaehan4707** [boostcampwm2023/and07-MindSync#130]
## Description
스페이스 추가하기
## TODO 
- [x] 사이드바에서 추가버튼을 누르면 다이얼로그 출력
- [x] 스페이스 만들기 기능
   - [x] 갤러리에서 사진 선택
   - [x] 이름 입력 
   - [x] UI 구현
 - [x] 스페이스 참여 기능
    - [x] 초대코드 비교 구현
    - [x] 스페이스 가입 기능
    - [x] UI 구현
