### ISSUE TITLE
스페이스 참여 API 적용

### ISSUE THREAD

**Issue by jaehan4707** [boostcampwm2023/and07-MindSync#151]
## Description
- 스페이스 참여 API 
## TODO 
- [x] getSpace API 생성
- [x] Repository, RepositoryImpl 구현
- [x] ViewModel 연결
- [x] 에러 처리
- [x] 다음화면에 Space 전달
- [x] 가입하기 처리
- [x] 아니오 처리
- [ ] 사이드바 스페이스 클릭 시 참여
