### ISSUE TITLE
단일 프로필 변경 및 유저 정보 가져오는 로직 변경

### ISSUE THREAD

**Issue by tnpfldyd** [boostcampwm2023/and07-MindSync#188]
## Description
멀티 프로필에서 단일 프로필로 변경한다.
access 토큰을 기반으로 되도록 로직을 변경한다.
## TODO
- [ ] 프로필 테이블 변경
- [ ] users.module email 기반으로 작성된 로직을 access 토큰 기반으로 변경
- [ ] profiles.module access 토큰 기반으로 변경
