### ISSUE TITLE
ProfileSpace 목록 API 적용

### ISSUE THREAD

**Issue by jaehan4707** [boostcampwm2023/and07-MindSync#209]
## Description
사이드바 스페이스 목록 보여주기
## TODO 
- [x] 스페이스 목록 API 구현
- [x] 에러 처리
- [x] viewModel 연결
- [x] 보드목록누르면 보드목록에 spaceId 전달 (SafeArgs)
- [x] 초대하기 누르면 spaceId전달(safeArgs)
