### ISSUE TITLE
0.3.2 버그 수정 및 피드백 반영

### ISSUE THREAD

**Issue by jaehan4707** [boostcampwm2023/and07-MindSync#229]
## Description
-  용자들이 사용해보고 느낀점에 대한 피드백 반영과 버그 수정
## TODO 
- [x] 채팅방 디자인 수정
- [x] 스페이스 클릭 이벤트 수정(텍스트 -> 이미지)
- [x] 스페이스 이미지 비율 수정
- [x] 스페이스 클릭 UI 반영
- [x] 프로필 닉네임 변경 시 시각화 처리
- [x] 보드 이미지 MultiPart로 서버에 전송
