### ISSUE TITLE
EditText enabeld 처리 및 닉네임을 다이얼로그 EditText에 설정

### ISSUE THREAD

**Issue by hegleB** [boostcampwm2023/and07-MindSync#245]
## Description
- EditText enabled 처리 및 닉네임을 다이얼로그 EditText에 설정

## TODO
- [x] 프로필 수정 enabled 
- [x] 스페이스 생성 enabled
- [x] 보드 생성 enabled
- [x] 초대 코드 enabled
- [x] 다이얼로그 EditText에 닉네임 설정
