### ISSUE TITLE
안드로이드 개발 환경 설정하기

### ISSUE THREAD

**Issue by jaehan4707** [boostcampwm2023/and07-MindSync#25]
## Description
안드로이드 개발 환경 설정 및 github action 추가
## TODO
- [x] github action ktlint 추가
- [x] minSdk 26으로 변경
- [x] github action auto-label 추가
- [x] 같이 사용할 공용 라이브러리 추가
  - [x] data binding, view binding
  - [x] hilt
  - [x] retrofit
  - [x] navigation
