### ISSUE TITLE
사이드바 동작 개선

### ISSUE THREAD

**Issue by jaehan4707** [boostcampwm2023/and07-MindSync#251]
## Description
- 사이드바 동작 개선
## TODO     
- [x] 햄버거(Navigation Drawer) 안보이게
- [x] 현재 참여한 스페이스가 없을때는 SpaceListFragment가 보여지게
- [x]  스페이스 나가기 시 참여한 스페이스가 없어짐
- [x]  첫 접속시 참여한 스페이스가 없음
- [x] 스페이스가 아무것도 없을 때 참여한 스페이스가 없음
