### ISSUE TITLE
다크 모드 적용

### ISSUE THREAD

**Issue by hegleB** [boostcampwm2023/and07-MindSync#258]
## Description
- 다크모드 적용
## TODO
- [x] 다크모드용 아이콘 추가
- [x] 다크모드용 colors 추가
- [x] 다크모드용 dialog 추가
