### ISSUE TITLE
앱 전반적인 디자인 수정

### ISSUE THREAD

**Issue by jaehan4707** [boostcampwm2023/and07-MindSync#272]
## Description
- 앱 디자인 수정
## TODO 
- [x] 사이드바 유저 목록 디자인 수정
- [x] 사이드바 스페이스 이름 추가
- [x] 온보딩 화면 텍스트 변경
- [x] 스트링.xml 분리하기
- [x] 프래그먼트 이름 상단에 출력
- [x] 토스트 메시지 수정
