### ISSUE TITLE
0.3.4 버그 수정

### ISSUE THREAD

**Issue by jaehan4707** [boostcampwm2023/and07-MindSync#286]
## Description
0.3.4 버그 수정
## TODO 
- [x] 휴지통 화면 보드 클릭시 앱 종료 버그 수정
- [x] 앱 타이틀 메시지 버그 수정
- [x] 선택된 스페이스 유지 안되는 현상 해결
