### ISSUE TITLE
스페이스,보드,유저 이름 크기 제한하기

### ISSUE THREAD

**Issue by jaehan4707** [boostcampwm2023/and07-MindSync#292]
## Description
- 앱 글자 수 제한
## TODO 
- [x] 길어지는 글자 ... 처리
- [x] 스페이스 추가 글자 수 대응
- [x] 보드 추가 글자 수 대응
- [x] 프로필 편집 글자 수 대응
