### ISSUE TITLE
Jetpack Compose 설정

### ISSUE THREAD

**Issue by hegleB** [boostcampwm2023/and07-MindSync#312]
## Description
- Jetpack Compose로 마이그레이션 하기 위한 설정
## TODO
- [x] kotlin 버전 변경
- [x] gradle.kts에서 compose 관련 추가
- [x] 디자인 시스템 구축(Color, Theme, Type)
- [x] Jetpack Compse 관련 Base 추가
