### ISSUE TITLE
스페이스 추가 JetpackCompose로 마이그레이션 하기

### ISSUE THREAD

**Issue by jaehan4707** [boostcampwm2023/and07-MindSync#322]
## Description
- xml로 되어 있는 스페이스 추가 UI를 Jetpack Compose로 마이그레이션
## TODO
- [x] TopBar
   - [x] 뒤로가기 버튼 구현
- [x] Image
   - [x] PhotoPicker 연결
   - [x] Url 받아와서 이미지 띄우기
   - [x] defaultImage 띄우기
- [x] TextFiled
   - [x] hint 텍스트 설정
   - [x] space 이름 입력
   - [x] 글자 수 판단
- [x] UiEvent 처리
   - [x] Success
   - [x] Error
