### ISSUE TITLE
노드 드로잉 알고리즘 구현 (childNode 위치 결정, branch 위치 결정)

### ISSUE THREAD

**Issue by yang1318** [boostcampwm2023/and07-MindSync#6]
## Description
ChildNode들의 크기에 따라 위치 자동 선정

## TODO 
- [x] 위치 결정 알고리즘 작성 (LayoutManager)
- [ ] 알고리즘 개선
  - [ ] Max 구하도록 수정
  - [ ] Node에 id값 생기면 높이값 측정때 메모이제이션 도전
