### ISSUE TITLE
노드 커스텀뷰 그리기

### ISSUE THREAD

**Issue by yang1318** [boostcampwm2023/and07-MindSync#7]
## Description
마인드맵에서 노드 부분에 대한 커스텀 뷰 기능 구현

## TODO
- [x] 노드 데이터 구조를 통해 커스텀뷰 그리기
- [x] dp2px, px2dp
- [x] depth 별로 자동 색상 할당
