### ISSUE TITLE
커스텀뷰 리팩토링

### ISSUE THREAD

**Issue by jaehan4707** [boostcampwm2023/and07-MindSync#77]
## Description
커스텀뷰에서 뷰모델을 참조하는 부분 리팩토링
## TODO
- [x] CustomView ViewModel 주입 제거
- [x] MindmapContainer ViewModel 주입 제거
- [x] MindmapContainer LineView,NodeView 주입 제거
- [x] ZoomLayout ViewModel 주입 제거
