### ISSUE TITLE
로그인 서버 API 연동

### ISSUE THREAD

**Issue by yang1318** [boostcampwm2023/and07-MindSync#93]
## TODO 
- [ ] 서버로 간편 로그인/회원가입 한 정보 전달해주기
  - [ ] 프로필 사진, 이름 (자세한건 한번 더 물어보기)
- [ ] JWT 토큰 저장해두기 (안전하게)
