### ISSUE TITLE
로그인 화면 구성

### ISSUE THREAD

**Issue by yang1318** [boostcampwm2023/and07-MindSync#94]
## Description
- 카카오 로그인 버튼
- 구글 로그인 버튼

## TODO 
- [x] 로그인 화면 xml 구성
  - [x] 버튼은 공식 사이트에서 가져오기
- [x] 화면이 너무 빈다면 자신만의 역량으로 채우면 좋음
