### ISSUE TITLE
웹 소켓 통신으로 실제 서버와 메세지 주고받기

### ISSUE THREAD

**Issue by yang1318** [boostcampwm2023/and07-MindSync#97]
## Description
실제 기능이랑 연동 없이! 단순히 메세지만 주고받을 수 있다.

## TODO 
- [x] 서버에 메세지를 보낼 수 있다
- [x] 서버에서 메세지를 받을 수 있다
- [x] 클라이언트끼리 메시지를 보낼 수 있다.
- [x] 클라이언트끼리 메시지를 받을 수 있다.
